name: Publish Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Install DocFX
        run: dotnet tool install -g docfx

      - name: Restore and build metadata
        run: |
          export PATH="$PATH:~/.dotnet/tools"
          cd MyMath
          dotnet restore
          dotnet build

      - name: Build documentation
        run: |
          export PATH="$PATH:~/.dotnet/tools"
          cd MyMath
          docfx build

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./MyMath/_site
          force_orphan: true
          enable_jekyll: false
          commit_message: 'Deploy documentation - Sebastian Fuentes (2022073902)'
