name: Publish Docs

on:
  push:
    branches:
      - main  # o la rama que uses

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Install DocFX
        run: dotnet tool install -g docfx

      - name: Restore and build metadata
        run: |
          export PATH="$PATH:~/.dotnet/tools"
          cd MyMath
          docfx metadata

      - name: Build documentation
        run: |
          export PATH="$PATH:~/.dotnet/tools"
          cd MyMath
          docfx build

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./MyMath/_site
