name: Release NuGet Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    name: Build & Publish NuGet
    runs-on: ubuntu-latest

    env:
      NUGET_VERSION: 1.0.0-2022073902
      PROJECT_PATH: MyMath/Math.Lib/Math.Lib.csproj

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
        source-url: https://nuget.pkg.github.com/SebastianFuentesAvalos/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build project
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

    - name: Pack nuget package
      run: dotnet pack ${{ env.PROJECT_PATH }} --configuration Release --no-build -p:PackageVersion=${{ env.NUGET_VERSION }}

    - name: Publish to GitHub Packages
      run: dotnet nuget push **/*.nupkg --skip-duplicate --source "github"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.NUGET_VERSION }}
        name: Release ${{ env.NUGET_VERSION }}
        generate_release_notes: true
